export namespace constants {
  export const CONFIG_OPTIONS = 'CONFIG_OPTIONS';
  export const PASSWORD_REGEXP = `^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!?@#$%^&*()-_+=,./])(?=.{8,})`;
  export const USERNAME_REGEXP = `^[a-zA-Z0-9]+$`;
  export const VERIFY_EMAIL = 'verify-contact';
  export const VERIFY_PHONE = 'verify-phone';
  export const FORGET_PASSWORD = 'forgot-password';
  export const USER_LIMIT_EXCEEDED = 'user-limit-exceeded';
  export const ACCOUNT_DEACTIVATION = 'account-deactivation';
  export const ACCOUNT_REACTIVATION = 'account-reactivation';
  export const CHANGE_PASSWORD = 'change-password';
  export const VERIFY_PHONE_NUMBER = 'verify-phone-number';
  export const FORGET_PHONE_UMBER = 'forget-phone-number';
  export const CHANGE_PHONE_UMBER = 'change-phone-number';
  export const NOTIFICATION = 'notification';

  export const CHANGE_EMAIL = 'change-email';
  export const CHANGE_PHONE = 'change-phone';
  export const TEST_EMAIL = 'test-email';
  export const STATUS_UNKNOWN = 'unknown';
  export const STATUS_PENDING = 'pending';
  export const STATUS_SUCCESS = 'success';
  export const STATUS_SOLVED = 'solved';
  export const STATUS_APPROVED = 'approved';
  export const STATUS_VERIFIED = 'verified';
  export const STATUS_COMPLETED = 'completed';
  export const STATUS_UNREGISTERED = 'unregistered';
  export const STATUS_ENABLED = 'enabled';
  export const STATUS_DISABLED = 'disabled';
  export const STATUS_DELETED = 'deleted';
  export const STATUS_BLOCKED = 'blocked';

  export const APP_STATUS = 'not-read';
  export const STATUS_SUBMITTED = 'submitted';
  export const STATUS_FAILED = 'failed';
  export const STATUS_FAIL_SEND = 'failSend';
  export const STATUS_SUCCESS_SEND = 'successSend';
  export const STATUS_SUCCESS_GET = 'successGet';
  export const STATE_DEFAULT = 'default';
  export const STATE_NOT_DEFAULT = 'not-default';
  export const SOURCE_PRIMARY = 'primary';
  export const SOURCE_SECONDARY = 'secondary';
  export const STATUS_COMING_SOON = 'coming_soon';
  export const AUTH_SERVICE = 'AUTHService';
  export const INFO_SERVICE = 'InfoService';
  export const LEARNING_SERVICE = 'LearningService';
  export const SUBSCRIPTION_SERVICE = 'SubscriptionService';
  export const PURCHASE_SERVICE = 'PurchaseService';
  export const SUPPORT_SERVICE = 'SupportService';
  export const PAYMENT_SERVICE = 'PaymentService';
  export const WALLET_SERVICE = 'WalletService';
  export const WORKER_SERVICE = 'WorkerService';
  export const USER_SERVICE = 'UserService';
  export const ADMIN_ROLE = 'admin';
  export const USER_ROLE = 'user';
  export const MANAGER_ROLE = 'manager';
  export const TITLE = 'title';
  export const BODY = 'body';
  export const BODY_ITALICS = 'bodyItalics';
  export const BODY_BOLD = 'bodyBold';
  export const BODY_BULLET = 'bodyBullet';
  export const HEADER1 = 'header1';
  export const HEADER2 = 'header2';
  export const LINE = 'line';
  export const SUB_PAGE = 'subPage';
  export const SUB_PAGE_BULLET = 'subPageBullet';
  export const CASE = 'case';
  export const STATUTE = 'statute';
  export const GENDERS = ['male', 'female', 'other'];
  export const DEFAULT_ORDER_ASC = [['updatedAt', 'ASC']];
  export const SEQUENCE_ORDER_ASC = [['sequence', 'ASC']];
  export const SEQUENCE_ORDER_DESC = { order: { sequence: 'DESC' } };
  export const LAST_ITEMS_ATTRIBUTES = { include: ['sequence', 'createdAt'] };
  export const REMOVE = 'remove';
  export const ADD = 'add';
  export const TRIAL = 'trial';
  export const WEEKLY = 'weekly';
  export const MONTHLY = 'monthly';
  export const ANNUAL = 'annual';
  export const USER_FEEDBACK = 'userFeedback';
  export const TEMPLATE_CONTEXT = '{{content}}';
  export const EXCHANGE_WORKER = 'worker';
  export const EMAIL = 'email';
  export const PHONE = 'phone';
  export const SEND = 'send';
  export const RECEIVED = 'received';
  

  export const QUEUE_VERIFY_PHONE_NUMBER = 'verifyPhoneNumber';
  export const QUEUE_CHANGE_PHONE_NUMBER = 'changePhoneNumber';
  export const QUEUE_NOTIFICATION = 'notification';

  export const QUEUE_VERIFY_EMAIL = 'verifyContact';
  export const QUEUE_USER_LIMIT_EXCEEDED = 'userLimitExceeded';
  // user-limit-exceeded
  export const QUEUE_CHANGE_EMAIL = 'changeEmail';
  export const QUEUE_FORGET_PASSWORD = 'forgotPassword';
  export const QUEUE_ACCOUNT_DEACTIVATION = 'accountDeactivation';
  export const QUEUE_FORGET_PHONE_UMBER = 'forgotPassword';
  export const QUEUE_CHANGE_PASSWORD = 'changePassword';
  export const QUEUE_ACCOUNT_REACTIVATION = 'accountReactivation';
  export const IN_APP_PURCHASE_TYPE = 'inAppPurchases';
  export const IN_APP_PURCHASE_SUBMIT_TYPE = 'inAppPurchaseSubmissions';
  export const IN_APP_PURCHASE_PRICE_SCHEDULE_TYPE = 'inAppPurchasePriceSchedules';
  export const IN_APP_PURCHASE_PRICE_TYPE = 'inAppPurchasePrices';
  export const IN_APP_PURCHASE_PRICE_PINT_TYPE = 'inAppPurchasePrices';
  export const CONSUMABLE = 'CONSUMABLE';
  export const RENEWING_SUBSCRIPTION = 'RENEWING_SUBSCRIPTION';
  export const NON_CONSUMABLE = 'NON_CONSUMABLE';
  export const NON_RENEWING_SUBSCRIPTION = 'NON_RENEWING_SUBSCRIPTION';

  export const TRANSACTION_TYPE_WITHDRAW = 'withdraw';
  export const TRANSACTION_TYPE_DEPOSIT = 'deposit';

  export const NOTIFICATION_SUCCESS_WITHDRAW = 'successSendMoney';
  export const NOTIFICATION_FAILED_WITHDRAW = 'failSendMoney';
  export const NOTIFICATION_SUCCESS_DEPOSIT = 'getMoney';
  export const NOTIFICATION_FAILED_DEPOSIT = 'failGetMoney';
  export const NOTIFICATION_ADD_NEW_CONTACT = 'addNewConatct';
  export const NOTIFICATION_ADD_FAVORITE_CONTACT = 'addFavoritContact';
  export const NOTIFICATION_DELETE_FAVORITE_CONTACT = 'delateFavoritContact';
  export const NOTIFICATION_ADD_WALLET = 'addWalet';
  export const NOTIFICATION_DELETE_WALLET = 'delateWalet';
  export const NOTIFICATION_CHANGE_USERNAME = 'changeUsername';
  export const NOTIFICATION_CHANGE_PASSWORD = 'changePassword';
  export const NOTIFICATION_ACCOUNT_REACTIVATION = 'accountReactivation';
  export const NOTIFICATION_USER_REGISTER = 'userRegister';

  export const ACTION_TYPE = 'deleteAccount';

  export const EVENT_TAG_AUTH = 'auth-api';
  export const EVENT_TAG_MOBILE = 'mobile-api';
}
